import test from "node:test";
import assert from "node:assert/strict";
import { resetStoreForTests } from "../src/store.js";
import { createCertificate, getCertificate, listCertificates, setCertificateStatus, certificateInfo, prepareCertificateKey, getCertificateSecrets } from "../src/certificates.js";
test("certificate lifecycle is owner scoped",async()=>{resetStoreForTests();const c=await createCertificate({ownerId:"u1",domainId:"dom1",hostname:"app.example.com"});assert.equal(c.status,"pending");assert.equal((await getCertificate(c.id,"u2")),null);assert.equal((await listCertificates("u1")).length,1);const r=await setCertificateStatus(c.id,"u1","ready",{expiresAt:"2030-01-01T00:00:00.000Z"});assert.equal(r.status,"ready");assert.equal(r.expiresAt,"2030-01-01T00:00:00.000Z");});
test("certificate status patch cannot mutate protected ownership or secret fields",async()=>{resetStoreForTests();const c=await createCertificate({ownerId:"u1",domainId:"dom1",hostname:"app.example.com"});const r=await setCertificateStatus(c.id,"u1","ready",{ownerId:"u2",encryptedPrivateKey:"leak",expiresAt:"2030-01-01T00:00:00.000Z"});assert.equal(r.ownerId,"u1");assert.equal(r.encryptedPrivateKey,undefined);assert.equal(r.expiresAt,"2030-01-01T00:00:00.000Z");});
test("certificate info exposes safe capabilities",()=>{const i=certificateInfo();assert.equal(i.persistent,true);assert.ok(i.challengeTypes.includes("dns-01"));assert.ok(!JSON.stringify(i).includes("private"));});

test("certificate key preparation stores encrypted key and CSR without exposing private key",async()=>{resetStoreForTests();process.env.BHAI_ACME_MASTER_KEY="test-master";const c=await createCertificate({ownerId:"u1",domainId:"dom1",hostname:"app.example.com"});const prepared=await prepareCertificateKey(c.id,"u1");assert.equal(prepared.certificate.status,"ready");assert.match(prepared.csr,/^[A-Za-z0-9_-]+$/);const secrets=await getCertificateSecrets(c.id,"u1");assert.ok(secrets.privateKey);assert.ok(secrets.csr);const pub=await getCertificate(c.id,"u1");assert.equal(pub.encryptedPrivateKey,undefined);delete process.env.BHAI_ACME_MASTER_KEY;});
