import test from "node:test";import assert from "node:assert/strict";import {checkRateLimit,resetRateLimits} from "../src/rateLimit.js";
test("rate limiter blocks after configured limit",()=>{const old=process.env.BHAI_RATE_LIMIT_MAX;process.env.BHAI_RATE_LIMIT_MAX="2";resetRateLimits();assert.equal(checkRateLimit("u").allowed,true);assert.equal(checkRateLimit("u").allowed,true);assert.equal(checkRateLimit("u").allowed,false);if(old===undefined)delete process.env.BHAI_RATE_LIMIT_MAX;else process.env.BHAI_RATE_LIMIT_MAX=old;});
test("rate limits are isolated by identity",()=>{resetRateLimits();const old=process.env.BHAI_RATE_LIMIT_MAX;process.env.BHAI_RATE_LIMIT_MAX="1";assert.equal(checkRateLimit("a").allowed,true);assert.equal(checkRateLimit("b").allowed,true);if(old===undefined)delete process.env.BHAI_RATE_LIMIT_MAX;else process.env.BHAI_RATE_LIMIT_MAX=old;});

test("rate limiter rejects bucket exhaustion without unbounded growth",()=>{resetRateLimits();const oldMax=process.env.BHAI_RATE_LIMIT_MAX;const oldBuckets=process.env.BHAI_RATE_LIMIT_MAX_BUCKETS;const oldWindow=process.env.BHAI_RATE_LIMIT_WINDOW_MS;process.env.BHAI_RATE_LIMIT_MAX="100";process.env.BHAI_RATE_LIMIT_MAX_BUCKETS="2";process.env.BHAI_RATE_LIMIT_WINDOW_MS="60000";assert.equal(checkRateLimit("one").allowed,true);assert.equal(checkRateLimit("two").allowed,true);assert.equal(checkRateLimit("three").allowed,false);assert.equal(checkRateLimit("three").code,"RATE_LIMIT_CAPACITY");if(oldMax===undefined)delete process.env.BHAI_RATE_LIMIT_MAX;else process.env.BHAI_RATE_LIMIT_MAX=oldMax;if(oldBuckets===undefined)delete process.env.BHAI_RATE_LIMIT_MAX_BUCKETS;else process.env.BHAI_RATE_LIMIT_MAX_BUCKETS=oldBuckets;if(oldWindow===undefined)delete process.env.BHAI_RATE_LIMIT_WINDOW_MS;else process.env.BHAI_RATE_LIMIT_WINDOW_MS=oldWindow;});
test("invalid rate limit configuration falls back safely",()=>{resetRateLimits();const oldMax=process.env.BHAI_RATE_LIMIT_MAX;const oldWindow=process.env.BHAI_RATE_LIMIT_WINDOW_MS;process.env.BHAI_RATE_LIMIT_MAX="NaN";process.env.BHAI_RATE_LIMIT_WINDOW_MS="-1";const result=checkRateLimit("safe");assert.equal(result.allowed,true);assert.equal(result.remaining,119);if(oldMax===undefined)delete process.env.BHAI_RATE_LIMIT_MAX;else process.env.BHAI_RATE_LIMIT_MAX=oldMax;if(oldWindow===undefined)delete process.env.BHAI_RATE_LIMIT_WINDOW_MS;else process.env.BHAI_RATE_LIMIT_WINDOW_MS=oldWindow;});


test("api-key identities can be independently bucketed",()=>{resetRateLimits();const old=process.env.BHAI_RATE_LIMIT_MAX;process.env.BHAI_RATE_LIMIT_MAX="1";assert.equal(checkRateLimit("api:key-a").allowed,true);assert.equal(checkRateLimit("api:key-a").allowed,false);assert.equal(checkRateLimit("api:key-b").allowed,true);if(old===undefined)delete process.env.BHAI_RATE_LIMIT_MAX;else process.env.BHAI_RATE_LIMIT_MAX=old;});
